<a href="https://colab.research.google.com/github/ravi18kumar2021/30Days-DS-to-GenAI/blob/main/Day03/Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# importing required libraries
import numpy as np
import pandas as pd

In [3]:
np.random.seed(42) # used for generate same random values
products = ['Laptop', 'Phone', 'Tablet', 'Monitor', 'Keyboard', 'Mouse']
categories = ['Electronics', 'Accessories']
dates = pd.date_range(start='2024-01-01', periods=20, freq='D')

data = {
    'OrderID': np.arange(1001, 1021),
    'Product': np.random.choice(products, 20),
    'Category': np.random.choice(categories, 20),
    'Quantity': np.random.randint(1, 5, size=20),
    'UnitPrice': np.random.randint(50, 1500, size=20),
    'OrderDate': dates
}
df = pd.DataFrame(data)
df.head()

   OrderID   Product     Category  Quantity  UnitPrice  OrderDate
0     1001   Monitor  Electronics         3        291 2024-01-01
1     1002  Keyboard  Electronics         2        826 2024-01-02
2     1003    Tablet  Accessories         3       1419 2024-01-03
3     1004  Keyboard  Accessories         4        614 2024-01-04
4     1005  Keyboard  Accessories         3        947 2024-01-05

In [4]:
# set OrderID as index for convenient
df = df.set_index('OrderID')
df.head()

          Product     Category  Quantity  UnitPrice  OrderDate
OrderID
1001      Monitor  Electronics         3        291 2024-01-01
1002     Keyboard  Electronics         2        826 2024-01-02
1003       Tablet  Accessories         3       1419 2024-01-03
1004     Keyboard  Accessories         4        614 2024-01-04
1005     Keyboard  Accessories         3        947 2024-01-05

In [5]:
# get number of rows and columns
df.shape

(20, 5)

In [6]:
# get statistics destributions of data
df.describe()

        Quantity    UnitPrice            OrderDate
count  20.000000    20.000000                   20
mean    2.600000   891.800000  2024-01-10 12:00:00
min     1.000000    84.000000  2024-01-01 00:00:00
25%     1.750000   600.000000  2024-01-05 18:00:00
50%     3.000000   976.000000  2024-01-10 12:00:00
75%     3.250000  1237.500000  2024-01-15 06:00:00
max     4.000000  1463.000000  2024-01-20 00:00:00
std     1.142481   458.249599                  NaN

In [7]:
# get to know the data types of each column
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20 entries, 1001 to 1020
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Product    20 non-null     object
 1   Category   20 non-null     object
 2   Quantity   20 non-null     int64
 3   UnitPrice  20 non-null     int64
 4   OrderDate  20 non-null     datetime64[ns]
dtypes: datetime64[ns](1), int64(2), object(2)
memory usage: 960.0+ bytes

In [8]:
# see the counts of each product
df['Product'].value_counts()

Product
Keyboard    5
Tablet      5
Monitor     4
Phone       3
Mouse       3
Name: count, dtype: int64

In [9]:
# see the counts of each category
df['Category'].value_counts()

Category
Accessories    11
Electronics     9
Name: count, dtype: int64

In [12]:
# if we try to combine both the above two (products count of each category)
df.groupby(['Category', 'Product'])['Quantity'].count()

Category     Product
Accessories  Keyboard    3
             Monitor     2
             Mouse       2
             Phone       2
             Tablet      2
Electronics  Keyboard    2
             Monitor     2
             Mouse       1
             Phone       1
             Tablet      3
Name: Quantity, dtype: int64

In [14]:
# let's find top selling product
df.head()

          Product     Category  Quantity  UnitPrice  OrderDate
OrderID
1001      Monitor  Electronics         3        291 2024-01-01
1002     Keyboard  Electronics         2        826 2024-01-02
1003       Tablet  Accessories         3       1419 2024-01-03
1004     Keyboard  Accessories         4        614 2024-01-04
1005     Keyboard  Accessories         3        947 2024-01-05

In [16]:
df.groupby('Product')['Quantity'].sum().sort_values(ascending=False)

Product
Tablet      14
Keyboard    11
Phone       11
Monitor     10
Mouse        6
Name: Quantity, dtype: int64

In [19]:
# create a new column with the name TotalPrice
df.loc[:, 'TotalPrice'] = df['Quantity'] * df['UnitPrice']
df.head()

          Product     Category  Quantity  UnitPrice  OrderDate  TotalPrice
OrderID
1001      Monitor  Electronics         3        291 2024-01-01         873
1002     Keyboard  Electronics         2        826 2024-01-02        1652
1003       Tablet  Accessories         3       1419 2024-01-03        4257
1004     Keyboard  Accessories         4        614 2024-01-04        2456
1005     Keyboard  Accessories         3        947 2024-01-05        2841

In [20]:
# category wise revenue
df.groupby('Category')['TotalPrice'].sum()

Category
Accessories    27162
Electronics    17380
Name: TotalPrice, dtype: int64

In [22]:
# product wise revenue
df.groupby('Product')['TotalPrice'].sum().sort_values(ascending=False)

Product
Phone       12495
Tablet       9528
Keyboard     8661
Monitor      7856
Mouse        6002
Name: TotalPrice, dtype: int64

In [23]:
# Total revenue per day
df.groupby('OrderDate')['TotalPrice'].sum()

OrderDate
2024-01-01     873
2024-01-02    1652
2024-01-03    4257
2024-01-04    2456
2024-01-05    2841
2024-01-06    5652
2024-01-07     564
2024-01-08    1440
2024-01-09    3015
2024-01-10     558
2024-01-11    2475
2024-01-12     252
2024-01-13     255
2024-01-14    1154
2024-01-15    4383
2024-01-16    2150
2024-01-17    4284
2024-01-18    1463
2024-01-19    2460
2024-01-20    2358
Name: TotalPrice, dtype: int64

In [27]:
# filter top 10 dates
df.groupby('OrderDate')['TotalPrice'].sum().sort_values(ascending=False).head(10)

OrderDate
2024-01-06    5652
2024-01-15    4383
2024-01-17    4284
2024-01-03    4257
2024-01-09    3015
2024-01-05    2841
2024-01-11    2475
2024-01-19    2460
2024-01-04    2456
2024-01-20    2358
Name: TotalPrice, dtype: int64

In [31]:
# since, there is no missing values in our dataset to perform data cleaning, let's add some missing values
df.loc[np.random.choice(df.index, 3, replace=False), 'Quantity'] = np.nan
df.loc[np.random.choice(df.index, 2, replace=False), 'UnitPrice'] = np.nan
df.head()

          Product     Category  Quantity  UnitPrice  OrderDate  TotalPrice
OrderID
1001      Monitor  Electronics       3.0      291.0 2024-01-01         873
1002     Keyboard  Electronics       NaN      826.0 2024-01-02        1652
1003       Tablet  Accessories       3.0     1419.0 2024-01-03        4257
1004     Keyboard  Accessories       NaN      614.0 2024-01-04        2456
1005     Keyboard  Accessories       NaN      947.0 2024-01-05        2841

In [32]:
df.isnull().sum()

Product       0
Category      0
Quantity      3
UnitPrice     2
OrderDate     0
TotalPrice    0
dtype: int64

In [34]:
# let's fill Quantity Column with its mean
df.loc[:, 'Quantity'] = df['Quantity'].fillna(df['Quantity'].mean())
df['Quantity'].isnull().sum()

np.int64(0)

In [36]:
# let's drop rows having missing values
df = df.dropna()
df.shape

(18, 6)